// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rneucmglencppxhghpci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJuZXVjbWdsZW5jcHB4aGdocGNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MTY2NjksImV4cCI6MjA2NzM5MjY2OX0.YPzBO9J9w-Z2HXgOBV_2_R8UJpMWyTaW5JMJ7y5TXJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});